version: "3.7"

services:
  harmoni_full:
    container_name: harmoni_full
    build:
      context: .
      dockerfile: dockerfiles/harmoni/noetic/full/dockerfile
      network: host
    image: harmoni02/harmoni2.0:full
    init: true
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
      ROS_DISTRO: noetic
      ROS_MASTER_URI: http://localhost:11311
      IS_DOCKER_ENV: "true"
      ROS_HOSTNAME: localhost
      CATKIN_WS: harmoni_catkin_ws
    privileged: true
    network_mode: "host"
    hostname: harmoni_full
    ports:
      - "11312:11312"
      - "33691:33691"
      - "8081:8081"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    volumes:
      - ../HARMONI/:/root/local_mount/HARMONI/
      # Configuration
      - ~/.aws:/root/.aws/
      - /home/massimiliano/.gcp/:/root/.gcp
      # Other
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/harmoni_catkin_ws/src/HARMONI
    command: tail  -f /dev/null

  