pytree:
  default_param:
    interaction: "guy_thp" #or meditation or ppi
    user_name: "Michelle"
    session: "session1" #session1_empathic, session1
    researcher_name: "Micol"
    scene: 0
    condition :  0 #0: non-empathic, 1: empathic

