FROM harmoniteam/harmoni:noetic-full

RUN \
    PIP_INSTALL="python3.8 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    opensmile \
    tensorflow \
    torch \
    torchaudio \
    onnxruntime==1.15 \
    py_trees 


CMD ["/bin/bash"]