FROM harmoniteam/harmoni:noetic-full

RUN \
    PIP_INSTALL="python3.8 -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
    facechannel==0.0.2 \ 
    numpy==1.19.5 \
    protobuf==3.20.1 \
    py_trees


CMD ["/bin/bash"]